site_name: Monarch Web Framework
site_description: A back-to-basics framework for the modern web.
docs_dir: _docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
    name: material
    features:
    logo: assets/logo.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    # highlight_js: true
    # hljs_style: github_dark
    # hljs_languages:
    #   - php

extra:
    homepage: https://lonnieezell.github.io/monarch

    social:
        - icon: fontawesome/brands/github
          link: https://github.com/lonnieezell/monarch
          name: GitHub

repo_url: https://github.com/lonnieezell/monarch
edit_uri: edit/develop/_docs/

extra_css:
    - assets/github-dark-dimmed.css

extra_javascript:
    - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/highlight.min.js
    - assets/js/hljs.js

nav:
    - Home: index.md
    - Routes: routes.md
    - Middleware: middleware.md
    - Views: views.md
    - Components: view_components.md
    - Database:
        - Getting Started: database/connections.md
        - Running Queries: database/queries.md
        - Query Builder: database/query_builder.md
        - Migrations: database/migrations.md
        - Extending: database/extending.md
    - Helpers:
        - Files: helpers/files.md
        - Strings: helpers/str.md
